name: Build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
         - {target: linux-x64}
         - {target: linux-arm64}
         - {target: darwin-x64}
         - {target: darwin-arm64}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup node 20.x
      uses: actions/setup-node@v3
      with:
          node-version: 20.x
    - name: Setup TT
      run: |
        curl -L https://tarantool.io/release/3/installer.sh | bash
        sudo apt-get install tt
    - name: Build
      run: npm i
    - name: Lint
      run: npm run lint
    - name: Package
      run: npx vsce package -o tarantool-vscode-${{ matrix.target }}.vsix --target ${{ matrix.target }}
    - name: Test
      run: xvfb-run -a npm run test
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Tarantool VSCode ${{ matrix.target }}
        path: ${{ github.workspace }}/tarantool-vscode*.vsix
