name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup node 20.x
      uses: actions/setup-node@v3
      with:
          node-version: 20.x
    - name: Build
      run: npm i
    - name: Lint
      run: npm run lint
    - name: Bulid
      run: npm run compile
    - name: Package
      run: npm run vscode:prepublish
